name: MIE_Converter
main: FaigerSYS\MIE_Converter\MIE_Converter
version: "1.0.1"
api: ["2.0.0", "3.0.0", "3.0.0-ALPHA1", "3.0.0-ALPHA2", "3.0.0-ALPHA3", "3.0.0-ALPHA4", "3.0.0-ALPHA5", "3.0.0-ALPHA6", "3.0.0-ALPHA7", "3.0.0-ALPHA8", "3.0.0-ALPHA9", "3.0.0-10"]
load: POSTWORLD
author: FaigerSYS
description: "Addon for MapImageEngine to convert images to .mie format"

permissions:
  mapimageengine.convert:
    default: op
    description: "Allows command usage (/mieconvert)"
